### ISSUE TITLE
Add support for emphasis rolls

### ISSUE THREAD

**Issue by JamieBallingall** [fponticelli/dicerun-ts#1]
A new idea has been floating about in D&D circles: the emphasis roll. You roll two d20 and take the one that is furthest from 10, rerolling draws. See [https://homebrewery.naturalcrit.com/share/wyL-vuEIDrbC](https://homebrewery.naturalcrit.com/share/wyL-vuEIDrbC).

Is there a way to model this behavior using the existing expression language? Or do we need to add some special syntax for this?

**Comment by fponticelli** [comment]
Not currently but adding it wouldn't be crazy hard. What a good syntax would be for it?

`2D20 furthest from 10 reroll` |  `2D20 furthest from 10 pick higher` could be the expanded form

Or simply `emphatic D20` | `em D20`

**Comment by fponticelli** [comment]
It is implemented :) ... here are some examples

* [`d20 emphasis`](https://dice.run/#/d/d20_emphasis)
* [`d20 emphasis low`](https://dice.run/#/d/d20_emphasis_low)
* [`d20 emphasis high`](https://dice.run/#/d/d20_emphasis_high)
* [`d20 furthest from 8`](https://dice.run/#/d/d20_furthest_from_8)

**Comment by fponticelli** [comment]
The curves look really nice ... and even nicer when you do things like `2d20 emphasis` :)
