### ISSUE TITLE
Dice graph breaking?

### ISSUE THREAD

**Issue by ExpTempus** [fponticelli/dicerun-ts#2]
The graphs for the dice rolls seem to break whenever the "bucket size" is more than one.

The graph starts normal and with expected results but then at some point in the sampling it will skip to the left and have the values around double the expected.

I have seen this happen primarily when rolling more than 10 d12s but also when combined with other dice pools in higher amounts.
![2023-05-03 19_33_26-dice run](https://user-images.githubusercontent.com/115100502/236011455-e5927b85-64ee-4f5a-acc5-6cf8a1946857.png)

**Comment by fponticelli** [comment]
That's definitely wrong 🙂 ... thank you for reporting, I will look into it.

**Comment by fponticelli** [comment]
This should be fixed now. Thank you!
