### ISSUE TITLE
Mislabeled buckets?

### ISSUE THREAD

**Issue by JamieBallingall** [fponticelli/dicerun-ts#5]
If I ask dice.run for information about 2d51 I get a distribution ranging from 2 to to 102 with a mode of 52, which is correct. However, if ask dice.run about 2d52 it says that the lowest value bucket is 2-3, the highest is 206-207 and the mode is 104-105. The lowest bucket is correct but the highest and modal buckets are about twice what they should be.

Something similar happens with 3d34 (correct) and 3d35 (about double).

The problem gets worse for higher dice rolls. 10d100 should have a mode of around 505 but shows something like 5050-5059 as the mode.

So these seems to be related to the labeling of the distributions. The error increases linearly with the bucket size. This is supported by the fact that the random result generator is unaffected and correctly generates values in range.

**Comment by fponticelli** [comment]
This should be fixed now. Thank you!
